- Cargo.toml
Allow to choose the SSL backend. By default it's `native-tls`, but it can be set to `rustls-tls` in order to not depend on the OpenSSL stack of the system.
```release-note
Allow to choose the SSL stack by adding a `native-tls` or `rustls-tls` feature
```
> Add option to build with rustls-tls support

- Cargo.toml
- src/cosign/client.rs
- src/registry.rs
Depends on: https://github.com/sigstore/sigstore-rs/pull/13
Depends on a release of the `oci-distribution` crate that contains https://github.com/krustlet/oci-distribution/pull/8.
Make `accept_invalid_hostnames` optional, given it's only used in the `openssl` backend. When `oci-distribution` is released with the mentioned commit (ca1fc724308ed183b42b3239e49c1b23ef183524), the `accept_invalid_hostnames` will **only and only** exist in the struct if the chosen SSL backend is `openssl`.
Signed-off-by: Rafael Fernández López <ereslibre@ereslibre.es>
> Make accept_invalid_hostnames conditional

- Cargo.toml
- examples/verify/main.rs
- src/cosign/bundle.rs
- src/cosign/client.rs
- src/cosign/client_builder.rs
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/crypto.rs
- src/errors.rs
- src/lib.rs
- src/mock_client.rs
- src/registry.rs
- src/tuf/mod.rs
- src/tuf/repository_helper.rs
Do not rely on `anyhow::Result` inside of public APIs. This makes error handling uglier for consumers of the library.
Instead, provide custom errors and use them inside of all the public facing APIs.
> Better error handling

- Cargo.toml
- Makefile
- examples/verify/main.rs
- src/cosign/bundle.rs
- src/cosign/client.rs
- src/cosign/client_builder.rs
- src/cosign/constants.rs
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/cosign/verification_constraint.rs
- src/crypto.rs
- src/errors.rs
- src/lib.rs
- src/registry.rs
First of all, sorry about the large amount of changes... Unfortunately the old code was too limited as we realized when using that inside of Kubewarden.
Prior to this commit:
* The email used to verify a keyless signature had to be specified inside of the `ClientBuilder`. That meant that, to verify the presence of multiple emails, multiple clients had to be created. That was a poor UX
* The library didn't parse some important data provided by the signature certificates: the URI and the OIDC issuer. These are required to build more flexible verification checks
In addition to addressing the previous limitations, this commit introduces the following changes:
* It's possible to define a series of Verification Constraints, which allows multiple requirements can be enforced against the list of …
>  Big code refactoring: better handling of verification

- Cargo.toml
Ensure we get a fix that just got merged on the main branch, this is needed to properly build with rustls.
> Update oci-distribution revision

- .github/workflows/auto-publish-crates-upon-release.yml
Creates a Github action to automatically `cargo publish` each new release to crates.io.
The version number of the crate in the Cargo.toml file will have to be updated prior to the new release for the action to work.
Also, a Github secret for the crates.io API token needs to be set up so that there's authorization to publish the update. Currently, the secret is named CARGO_API_TOKEN in the .yml file.
Fixes #30 
```release-note
```
> Create GH action to auto publish crate upon release

- src/cosign/signature_layers.rs
This is required to make writing of unit tests easier for 3rd parties defining their own constraint validators.
> Change the visibility of `SignagureLayer` attributes

- src/cosign/mod.rs
Remove negation inside of the `match` for constraints. This means that verified layers will get correctly passed to `any()`.
Remove negation on the `constraints.iter.any()`. this means that when a layer is verified (returning true in the closure), it well get added correctly to the layers vector.
All in all, this gives us the correct behaviour: if there's some verified signatures, they get added.
If there's no verified signatures, we return `SigstoreError::SigstoreNoVerifiedLayer`. In the past, we where almost always returning that error instead.
Fix test for correct behaviour.
```release-note
- fx: `cosign::filter_signature_layers()` when no match
```
> fix: cosign::filter_signature_layers() when no match 

- Makefile
- examples/verify/main.rs
- src/cosign/client.rs
- src/cosign/mod.rs
- src/cosign/verification_constraint.rs
- src/errors.rs
- src/lib.rs
BREAKING CHANGE: Drop `cosign::filter_signature_layers` in favour of
`cosign::verify_constraints()`, that returns a new `SigstoreVerifyConstraintsError`
which contains references to unsatisfied constraints.
The relationship between layers and constraints is not injective (e.g:
AnnotationsVerifier), hence no image verification info could be derived
from the number of layers verified.
With unsatisfied constraints, we know that 0 means the image is
verified.
If we have some unsatisfied constraints, we can use them to provide info
on why we failed verification.
Add a test and consume changes.
Fixes https://github.com/sigstore/sigstore-rs/issues/41.
```release-note
fix!: Drop filter_signature_layers() for verify_constraints()
```
> fix!: Drop filter_signature_layers() for verify_constraints() 

- .github/workflows/docs.yml
The `docs` GitHub Action job has been failing lately. We have changed the default settings of the `GITHUB` token to have read-only capabilities.
This breaks the `docs` action, because the action performs the following operation:
* Checkout the code
* Render the docs
* Push the new docs to a dedicated branch of the repository
The last step is broken by the lack of write permissions associated with the GITHUB token.
This commits adds the permissions that are required to perform commits.
Hopefully this is going to be enough, if not I'll create a new PR which instead uses a deployment key.
> Ensure docs are automatically published

- Cargo.toml
- examples/verify/main.rs
- src/cosign/client.rs
- src/cosign/client_builder.rs
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/crypto/certificate.rs
- src/crypto/certificate_pool.rs
- src/crypto/mod.rs
- src/errors.rs
- src/registry.rs
- src/tuf/constants.rs
- src/tuf/mod.rs
- src/tuf/repository_helper.rs
Fulcio has recently introduced a new root CA to issue certificates. Prior to this commit, the code was making use only of the initial root CA.
Because of that, recent keyless signatures were considered not valid.
Now the code is taking into account of the root CAs that Fulcio used over the time.
Fixes https://github.com/sigstore/sigstore-rs/issues/32
```release-note
* Fix(TUF): fetch all the Fulcio certificates found inside of the TUF repository
* Fix(Verification): ensure all the Fulcio root certificates are used to verify signatures. This fixes issue #32
```
> fix handling of fulcio certificates

- .github/workflows/docs.yml
Using permissions wasn't enough to allow the GitHub Action to publish the docs.
This commit switches away from the GITHUB_TOKEN, and uses a dedicated deployment key.
For more details, see https://github.com/sigstore/sigstore-rs/pull/44
> Fix docs publishing

- Cargo.toml
Consume it from crates.io, the RC builds are already available over there.
> Update picky dependency

- Cargo.toml
- examples/verify/main.rs
- src/cosign/client_builder.rs
- src/registry/config.rs
- src/registry/mod.rs
- src/registry/oci_caching_client.rs
- src/registry/oci_client.rs
Allow end consumers of the library to create a `cosign::Client` that caches the response it gets from OCI registries.
The cache entries are automatically expired after 60 seconds.
This can be useful in certain scenarios, like when writing code that can verify the same container image, but with different constraints.
Imagine the following scenario: write a REST API that exposes sigstore verification capabilities.
In this case, the REST API can receive multiple verification requests of the same image, but each time with slightly different verification constraints.
Thanks to the registry caching feature, the REST server would significantly reduce the number of interactions with the remote OCI registry. That would lead to shorter response times and higher request per seconds.
To be completely …
> OCI caching client

- examples/openidflow/main.rs
- src/errors.rs
- src/oauth/openidflow.rs
Alongside the claims (containing the scopes) we also need the`id_token`.
Also changes `println!` with `tracing::error`
> Return the ID token

- .github/workflows/auto-publish-crates-upon-release.yml
- .github/workflows/docs.yml
- .github/workflows/security-audit-cron.yml
- .github/workflows/security-audit-reactive.yml
- .github/workflows/tests.yml
as a best practice, we should pin the actions to use the git hash instead of the tag or `main`.
also, this makes it similar to the other workflows we have in the sigstore org.
- pin the github actions to use the git hash
n/a
```release-note
NONE
```
> pin the github actions to use the git hash

- Cargo.toml
- src/cosign/signature_layers.rs
- src/crypto/certificate.rs
Address the compilation issues introduced by the API changes.
This supersedes https://github.com/sigstore/sigstore-rs/pull/57
> Update to latest version of x509-parser crate

- .github/workflows/tests.yml
- src/cosign/signature_layers.rs
- src/lib.rs
- src/registry/oci_caching_client.rs
- src/simple_signing.rs
- src/tuf/constants.rs
I added exceptions to instances of unwrap that have a comment
justifying use.
We now need to either toggle the last to handling the Option / Result or
use except.
Test uses of unwrap will be ignored (as will examples)
Blocks unsafe
> Block unsafe and have clippy warn on unsafe|panic

- src/cosign/client.rs
- src/cosign/constants.rs
- src/cosign/signature_layers.rs
The certificates issued by Fulcio include some custom x509 extensions when `cosign verify` is ran inside of a GitHub Action.
Starting from this commit, all these extra attributes are extracted from the certificate and stored inside of the `CertificateSignature` object.
This allows the creation of more fine-tuned validation constraints for signatures produced inside of GitHub Actions.
> Extract all the GitHub related information from signature certs

- Cargo.toml
- README.md
Add a `license` entry inside of Cargo.toml. This is needed in order to publish the crate on creates.io
Unfortunately `cargo publish --dry-run` doesn't report this issue, this is something enforced by crates.io at "push" time
> Release v0.3.1

- .cargo/audit.toml
- Cargo.toml
This PR fixes the broken unit tests and makes `cargo audit` happy.
They were failing because the `picky` crate was not built with the `ec` feature enabled. That caused the verification of all the certificates using ECDSA keys to fail.
Cargo audit was previously failing because of two rust security issues:
* [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159): this affected chrono release prior to 0.4.19.
* [RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071): this is an issue affecting old release of the `time` crate
chrono release 0.4.20 fixes the first issue ([RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159)).
However, chrono dependency on the old time 0.1 release is still present, which makes `cargo audit` report the second issue …
> fix broken ci

- Cargo.toml
Changes since v0.3.2:
* Ensure certificates using ECDSA keys keep working (bf908074203326e9d51c8ad7ee8c4298149cee66)
* Extend README to cover OIDC usage
* Update dependencies
I think we should really push out a new release to ensure certificate verification keeps working.
> Tag v0.3.3 release

- .github/workflows/tests.yml
- add clippy config and ignore derive_partial_eq_without_eq
> add clippy config and ignore derive_partial_eq_without_eq

- .cargo/audit.toml
Security CI runs are failing due to RUSTSEC-2021-0139
RUSTSEC-2021-0139 is flagged from ansi_term, which is a transient
dependency on tracing-subscriber. As tracing-subscriber is a
dev-dependency, I think we can safely add this to the ignore flag.
No vulnerabilities exist in ansi-term, the warning is there as the crate is
unmaintained at present.
> Add RUSTSEC-2021-0139 to audit.toml

- Cargo.toml
Upgrade to the latest stable release. This is required to have a more recent version of the chrono dependendency.
> Update tough dependency

- Cargo.toml
- examples/fulcio/cert/main.rs
- src/fulcio/mod.rs
- src/fulcio/oauth.rs
- src/lib.rs
- src/oauth/openidflow.rs
Fixes https://github.com/sigstore/sigstore-rs/issues/131
Creates an async Fulcio client to make working with Fulcio more straightfoward.
* Fulcio client for exchanging public key for signed certificate added.
Rust docs provided.
> Fulcio client

- Cargo.toml
Require only major and minor version, don't have the patch release hardcoded.
This is done to the following dependencies:
* oci-distribution
* olpc-cjson
* tough
> chore: relax some dependencies version

- src/fulcio/mod.rs
For some unexplained reasons, using the library inside of another project caused this error:
```console
error[E0015]: cannot call non-const fn `HeaderName::from_static` in constants
--> /home/flavio/.cargo/registry/src/github.com-1ecc6299db9ec823/sigstore-0.5.1/src/fulcio/mod.rs:22:46
|
22 | const CONTENT_TYPE_HEADER_NAME: HeaderName = HeaderName::from_static("content-type");
|                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: calls in constants are limited to constant functions, tuple structs and tuple variants
For more information about this error, try `rustc --explain E0015`.
```
This happened with sigstore-rs >= 0.5, but it was not detected by cargo check despite the same version of rustc and rust edition is used.
This commit addresses the …
> fix: address compilation error

- Cargo.toml
Ensure the openssl dependency is not introduced when the sigstore-rs library is built using rustls-tls.
> fix: rustls should not require openssl

- src/rekor/models/log_entry.rs
Signed-off-by: Lily Sturmann <lsturman@redhat.com>
I need to access some of these fields, and I think being able to do so would make sense.
> Add getter functions for LogEntry fields

- examples/rekor/create_log_entry/main.rs
- examples/rekor/search_log_query/main.rs
Currently, the following compiler warnings are being generated when building/running the tests:
```console
$ cargo t --no-run
Compiling sigstore v0.5.3 (/sigstore/sigstore-rs)
warning: unused import: `url::Url`
--> examples/rekor/search_log_query/main.rs:23:5
|
23 | use url::Url;
|     ^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `sigstore` (example "search_log_query") generated 1 warning warning: unused import: `url::Url`
--> examples/rekor/create_log_entry/main.rs:21:5
|
21 | use url::Url;
|     ^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `sigstore` (example "create_log_entry") generated 1 warning
Finished test [unoptimized + debuginfo] target(s) in 28.87s
Running unittests …
```
> Remove unused imports in examples/rekor

- CHANGELOG.md
- Cargo.toml
Fixes
=====
* Fix typo in cosign/mod.rs doc comment by @danbev in https://github.com/sigstore/sigstore-rs/pull/148
* Fix typo in KeyPair trait doc comment by @danbev in https://github.com/sigstore/sigstore-rs/pull/149
* Update cached requirement from 0.39.0 to 0.40.0 by @dependabot in https://github.com/sigstore/sigstore-rs/pull/154
* Fix typos in PublicKeyVerifier doc comments by @danbev in https://github.com/sigstore/sigstore-rs/pull/155
* Fix: CI error for auto deref by @Xynnn007 in https://github.com/sigstore/sigstore-rs/pull/160
* Fix typo and grammar in signature_layers.rs by @danbev in https://github.com/sigstore/sigstore-rs/pull/161
* Remove unused imports in examples/rekor by @danbev in https://github.com/sigstore/sigstore-rs/pull/162
* Update link to verification example by …
> Tag v0.6.0

- Cargo.toml
- examples/cosign/verify-bundle/.gitignore
- examples/cosign/verify-bundle/README.md
- examples/cosign/verify-bundle/main.rs
- examples/cosign/verify-bundle/run.sh
- src/cosign/bundle.rs
- src/cosign/mod.rs
This commit adds an example that uses `cosign sign-blob` with the `--bundle` option so that a bundle is generated. This bundle will then be used as an argument to verify-bundle, and it will be used to verify a blob.
NONE
NONE
----
I realize that this example is very different from the [verify example](https://github.com/sigstore/sigstore-rs/tree/main/examples/cosign/verify). I've tried to make the usage as simple as possible, but I realize that being new to the code base I might not have enough knowledge about how this could be improved. Hopefully others can provide feedback if there are better ways of doing this.
> Add cosign verify-bundle example

- src/cosign/bundle.rs
This commit updates the doc comment for the base64_signature field which I believe is incorrect 
(I'm the one to blame for this, sorry!).
NONE
NONE
> Fix incorrect base64_signature doc comment

- src/rekor/apis/mod.rs
Show the actual response status code, instead of `{error.status:?}`.
Currently, when a remote call fails with a client or server error, it shows a response error with the following message:
```
error in response: status code {{error.status:?}}
```
However, I do believe the actual intention (and what would be helpful), is to show the actual status code, instead of the literal string: `{error.status:?}`.
This PR fixes this issue, so that the error code gets shown.
Fix an issue where, instead of the actual error code, the literal string `{error.status:?}` was shown.
> fix: show actual response status field

- src/rekor/models/log_entry.rs
Signed-off-by: Jens Reimann <jreimann@redhat.com>
Not having access to these fields makes it hard to work with the data (like verifying).
> fix: make the fields accessible

- src/rekor/models/hashedrekord.rs
Signed-off-by: Jens Reimann <jreimann@redhat.com>
Make some more fields public. This is required if one wants to make use of the data in the `Hash` structure.
> fix: make fields of hash accessible

- examples/rekor/get_public_key/main.rs
As described in #105 the output provided by the example `get_public_key` was not pretty. It included quotation marks at the beginning and the and, as well as the newline characters `\n`. 
In addition this prevented piping the output of the example into a file, as it would include the quotation marks and the newline characters. Now using `cargo run --example get_public_key > key.pub` the public key can be stored in a file in the PEM format.
In addition it can be useful to directly store the public key in a file instead of piping to a file.  
The Rekor example `get_public_key` was expanded to:
* use `Display` printing 
* provide a command line option to store the public key in a file
Close #105
> Improve public key output and add file output

- src/rekor/apis/entries_api.rs
- src/rekor/models/hashedrekord.rs
- src/rekor/models/log_entry.rs
Signed-off-by: Neccolini <shun11202991@gmail.com>
closes #150 
Enable detailed information to be obtained when a `LogEntry` is retrieved, whereas previously only encoded `String` was available for the `Body` information.
> Changed the type of LogEntry.body from String to Body

- .github/workflows/tests.yml
- Cargo.toml
- examples/README.md
- examples/cosign/sign/README.md
- examples/cosign/verify/README.md
- examples/openidflow/README.md
- src/cosign/client_builder.rs
- src/crypto/mod.rs
- src/errors.rs
- src/lib.rs
- src/registry/mod.rs
This pr tries to divide different modules (like `fulcio`, `rekor` and `cosign`) into different features. The dependencies of the unenabled features will not be compiled to save space and time.
New features are introduced, including
- `full-native-tls`, `full-rustls-tls`: full stack
- `fulcio-native-tls`, `fulcio-rustls-tls`: fulcio
- `rekor-native-tls`, `rekor-rustls-tls`: rekor
- `cosign-native-tls`, `cosign-rustls-tls`: cosign
- `mock-client-native-tls`, `mock-client-rustls-tls`: mock client for test
- `cached-client`: whether uses `cached-client` option
Close https://github.com/sigstore/sigstore-rs/issues/187
> Add fine-grained features to control the compilation

- Cargo.toml
- src/cosign/client.rs
- src/lib.rs
Related to https://github.com/sigstore/sigstore-rs/issues/187
- TUF is a independent feature thus bring out of rekor
- Added `mock-client` feature to a test which depends on `mock-client`.
> fix: bring tuf feature out of rekor and add related docs

- Cargo.toml
- examples/fulcio/cert/main.rs
- src/cosign/bundle.rs
- src/cosign/constants.rs
- src/cosign/signature_layers.rs
- src/cosign/verification_constraint/certificate_verifier.rs
- src/crypto/certificate.rs
- src/crypto/certificate_pool.rs
- src/crypto/mod.rs
- src/crypto/signing_key/ecdsa/ec.rs
- src/crypto/signing_key/ed25519.rs
- src/crypto/signing_key/rsa/mod.rs
- src/crypto/verification_key.rs
- src/errors.rs
- src/fulcio/mod.rs
Replace `x509-parser` with `x509-cert`.
- `x509-cert` is from RustCrypto, and the replaced `x509-parser` depends on `ring`. This PR will help to get rid of `ring`.
- Add a test that converts a public key cert of ed25519 into a `CosignVerificationKey`
> Replace `x509-parser` with `x509-cert`

- src/lib.rs
This fixes the issue described in #214 by putting the parameters into the correct order.
Resolves: #214
Fixed parameter order for `sigstore::cosign::Client::trusted_signature_layers()` in documentation example causing `RegistryPullManifestError` when used.
This affects the **crate documentation**, but should not affect the documentation on https://docs.sigstore.dev
> Fix: Wrong parameter order inside documentation example.

- src/lib.rs
[src/lib.rs]
- Remove `get_timestamp_cert_chain` and `get_timestamp_response` functions
- Remove functions related to timestamping from `src/lib.rs`
- Fixes https://github.com/sigstore/sigstore-rs/issues/107
NONE
NONE
> Remove lines about timestamp in lib.rs

- Cargo.toml
Closes: #222
- Refer to #222
- This fixes the issue by forcing `ed25519` version to be 2.1.0, which allows `ed25519-dalek` to be compiled against 2.1.0 instead of the incompatible 2.2.0.
NONE
NONE
> Fix ed25519 version conflict

- .github/workflows/tests.yml
- Cargo.toml
- README.md
- examples/openidflow/openidconnect/main.rs
- src/cosign/client.rs
- src/cosign/mod.rs
- src/crypto/verification_key.rs
- src/fulcio/oauth.rs
- src/mock_client.rs
- src/oauth/openidflow.rs
- src/registry/mod.rs
- src/registry/oci_caching_client.rs
- src/registry/oci_client.rs
Enable support for compiling sigstore-rs to WASM, making it usable from browser applications and on wasm32 VMs.
Example application using the Yew framework: https://github.com/trustification/sigstore-search
Closes  #220
> Support compiling to wasm32 architectures

- src/rekor/models/log_entry.rs
Closes: https://github.com/sigstore/sigstore-rs/issues/243
This commit updates the LogEntry body field type to be an enum instead of a struct. This enum will contain a variant for the different types of rekords that can be stored in Rekor.
The motivation for this change is that currently only Hashedrekord::Spec are supported as that is the type spec field in the current Body struct. For further details please see the linked issue.
TODO:
NONE
> fix: make LogEntry Body an enum

- examples/cosign/sign/main.rs
- examples/cosign/verify/main.rs
- src/cosign/client.rs
- src/cosign/mod.rs
- src/cosign/payload/simple_signing.rs
- src/cosign/signature_layers.rs
- src/lib.rs
- src/registry/mod.rs
- src/registry/oci_reference.rs
This introduces a Newtype `OciReference` to the public API.
There are two motivations behind this change:
- improve the API to prevent errors such as #214 through a more descriptive type.
- The Newtype is a wrapper around the internally used `oci_distribution::Reference` type in order to prevent leaking this into the public API.
See also: #214 and #215
- Added type `OciReference` in `sigstore::registry::oci_reference` to represent OCI references in other APIs.
- `CosignCapabilities` trait: changed signature of functions `triangulate()`, `fetch_manifest_and_layers()`  `push_signature()`, parameters related OCI image references now have type `&OciReference` instead of `&str`.
- `SimpleSigning::new()`: changed type of `image_ref` to `&OciReference` from `&str` .
- …
> Introduce Newtype `OciReference` into API for OCI image references.

- src/tuf/constants.rs
The TUF root for the production instance of sigstore is now addressable via a CDN endpoint; this change uses the CDN instead of calling GCS directly via its HTTP endpoint
> Swap over to using CDN to fetch TUF metadata

- Cargo.toml
- examples/rekor/create_log_entry/main.rs
- src/crypto/certificate.rs
- src/crypto/verification_key.rs
This change makes minor source tweaks to upgrade the `der` dependency to version `0.7.5`.  It replaces the dependabot PR https://github.com/sigstore/sigstore-rs/pull/256 for which the CI builds are failing.
> upgrade 'der' to 0.7.5

- Cargo.toml
This very minor change avoid the warning when running `cargo test`:
```bash
$ cargo test --all
warning: unused manifest key: dependencies.chrono.feature
```
> remove unused 'clock' feature for chrono

- Cargo.toml
- src/crypto/signing_key/kdf.rs
- src/errors.rs
Update the [pkcs1](https://crates.io/crates/pkcs1) dependency to the latest version, `0.7.5` - with minor necessary source code adjustments.
Currently PR is cumulative with #259 - can either merge this one to cover both small changes, or I can rebase it one #259 is merged.
> update pkcs1 from 0.4.0 to 0.7.5

- Cargo.toml
since this crate is new and indicated as "experimental", suggesting to use the latest 2021 edition.
> use 2021 Rust edition

- Cargo.toml
- src/crypto/signing_key/kdf.rs
PR is a fixed version of #231 with the call to [scrypt::Params::new](https://docs.rs/scrypt/0.11.0/scrypt/struct.Params.html#method.new) modified for the crate's API change.
> update scrypt to 0.11.0, adapt for API change (fix #231)

- Cargo.toml
- examples/cosign/verify/main.rs
- examples/fulcio/cert/main.rs
- examples/rekor/create_log_entry/main.rs
- examples/rekor/search_log_query/main.rs
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/cosign/verification_constraint/certificate_verifier.rs
- src/crypto/certificate.rs
- src/crypto/signing_key/ecdsa/ec.rs
- src/crypto/signing_key/ed25519.rs
- src/crypto/signing_key/rsa/keypair.rs
- src/crypto/signing_key/rsa/mod.rs
- src/crypto/verification_key.rs
- src/errors.rs
Update to the latest version of a bunch of crypto libraries. These libraries, especially the ones that belong to RustCrypto, have to be updated at the same time.
There have been a lot of API changes and deprecation warnigns, which needed quite some adaptation of our codebase.
Moreover, remove `der` and `scrypt` deps.
These dependencies are also exported by the `x509-cert` crate. We're going to consume them via this crate to simply dependency management.
These two dependencies must move in sync with `x509-cert`, hence it makes a lot of sense to leverage the export provided by this crate.
> Update crypto deps

- Cargo.toml
- examples/rekor/create_log_entry/main.rs
Updates the example program create_log_entry to create the key pair used to sign and upload the data file into the Rekor transparency log. Therefore, the users do not need to create the files and generate the hashes required to create an transparency log entry.
Fix #104
> Update create_log_entry example to create key pair.

- src/cosign/client.rs
- src/cosign/mod.rs
- src/mock_client.rs
- src/registry/mod.rs
- src/registry/oci_caching_client.rs
- src/registry/oci_client.rs
After d9b198ae4530a63932d8d674b1dd033fc08b0dfe got merged, the `Sync` and `Send` supertraits got removed from the `ClientCapabilities` trait. This was done to ensure the code could build when the `wasm32` target is used.
Unfortunately, this makes impossible to send the cosign client between threads. This causes an error like the following one:
```
error: future cannot be sent between threads safely
the trait `Send` is not implemented for `(dyn sigstore::registry::ClientCapabilities + 'static)`
```
This commit fixes the issue by introducing conditional compilation checks.
> fix: ensure cosign client can be sent between threads

- Cargo.toml
Use latest RC of picky-rs. This RC now has elliptic curve support enabled by default, because of that the `ec` feature has been removed from the crate.
> chore(deps): update picky dependency

- CHANGELOG.md
- Cargo.toml
This is a patch release that bumps dependencies. The most significant upgrade is the `picky-rs` one.
> Release 0.7.2

- Cargo.toml
Enabling the default features of chrono causes the time 0.1 crate to be added as a transitive dependency.
This old version of time is affected by CVE RUSTSEC-2020-0071
Thanks to work done inside of chrono 0.4, there are high chances the majority of the codebases do not actually need it.
Building sigstore with only the cosign feature prevents the inclusion of the vulnerable time dependency.
This isn't unfortunately true when rekor is being used, because the openid crate brings the transitive dependency back.
> chore(deps): do not enable default features of chrono

- Cargo.toml
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/crypto/certificate_pool.rs
This PR performs small fixes:
- docs: fix broken links
- deps: update to latest stable versions of chrono and webpki. This also fixes the broken test seen on https://github.com/sigstore/sigstore-rs/pull/312
- deps: remove picky-rs dependency. This closes https://github.com/sigstore/sigstore-rs/issues/308
> Fix broken tests, update deps

- .cargo/audit.toml
[Current `cargo audit` workflow](https://github.com/trail-of-forks/sigstore-rs/actions/runs/7389952340/job/20103881623#step:3:9) is failing due to RSA timing sidechannel attack. Not relevant for this use (and to be refactored in #307), so add to `.cargo/audit.toml` ignorelist with rationale.
(CC @woodruffw)
> cargo audit: ignore RUSTSEC-2023-0071

- Cargo.toml
- src/cosign/client_builder.rs
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/cosign/verification_constraint/certificate_verifier.rs
- src/crypto/certificate_pool.rs
- src/registry/config.rs
- src/tuf/mod.rs
Signed-off-by: Jack Leightcap <jack.leightcap@trailofbits.com>
Adjacent effort to #307, reduce redundant rustls dependencies.
Update rustls-webpki to stable release ([changelog](https://github.com/rustls/webpki/releases/tag/v%2F0.102.1)),
and fold `rustls` deps together by removing explicit `rustls_webpki_types` dependency, instead using re-exported `webpki::types`.
NONE
> dep: update rustls-webpki, fold in pki_types

- Cargo.toml
- src/cosign/signature_layers.rs
- src/cosign/verification_constraint/certificate_verifier.rs
- src/crypto/certificate.rs
- src/crypto/mod.rs
This PR mainly fixes the lint error of new chrono `0.4.35` who brings some breakthrough APIs.
Also, a `dev-dependency` of `tokio` with feature `rt-multi-thread` and `rt` is added to make the `example`s builtable.
> lint: fix lint error of chrono and tokio

- Cargo.toml
Prepare 0.9.0 release
This is a minor release since some API have been changed.
== What's Changed
- sign: init by @jleightcap in https://github.com/sigstore/sigstore-rs/pull/310
- cargo audit: ignore RUSTSEC-2023-0071 by @jleightcap in https://github.com/sigstore/sigstore-rs/pull/321
- chore(deps): Update json-syntax requirement from 0.9.6 to 0.10.0 by @dependabot in https://github.com/sigstore/sigstore-rs/pull/319
- chore(deps): Update cached requirement from 0.46.0 to 0.47.0 by @dependabot in https://github.com/sigstore/sigstore-rs/pull/323
- chore(deps): Update serial_test requirement from 2.0.0 to 3.0.0 by @dependabot in https://github.com/sigstore/sigstore-rs/pull/322
- dep: update rustls-webpki, fold in pki_types by @jleightcap in https://github.com/sigstore/sigstore-rs/pull/324
- …
> Tag the 0.9.0 release

- .github/workflows/security-audit-cron.yml
- .github/workflows/security-audit-reactive.yml
The GH action of cargo audit is now provides by the maintainers of the project.
The previous actions we were using seems to not be maintained anymore.
> chore(deps): change provider of cargo-audit GH action

- examples/cosign/verify/main.rs
- src/lib.rs
- src/trust/mod.rs
`ManualTrustRoot` implements the `TrustRoot` trait, which requires the implemented to have multiple rekor keys. The `ManualTrustRoot` struct has now been updated to handle that, prior to that only one Rekor key was stored inside of a `ManualTrustRoot` instance.
> fix: allow ManualTrustRoot to have multiple rekor keys

- src/bundle/sign.rs
- src/bundle/verify/models.rs
- src/bundle/verify/verifier.rs
- src/crypto/keyring.rs
- src/crypto/mod.rs
- src/crypto/transparency.rs
- src/errors.rs
- src/fulcio/mod.rs
~~Blocked on #311.~~
Adds Signed Certificate Timestamp verification and hooks it up to the bundle signing flow. SCT verification ensures that the signing certificate in a given operation has been submitted to the Certificate Transparency log, which aids in the detection of malicious certificates and keeps Certificate Authorities like Fulcio honest.
* Implemented Signed Certificate Timestamp validation for certificates used in Sigstore Bundle operations.
No user-facing documentation needed, we automatically perform SCT validation when public `sign` and `verify` APIs are used.
> Signed Certificate Timestamp verification

- src/crypto/transparency.rs
Quick change to resolve a TODO: replace manually defined OIDs with their equivalents in `const-oid`.
CC @flavio
> transparency: pull OID constants from `const-oid`

- Cargo.toml
I noticed our Cargo.toml file needed some love:
- relax dependency versions: a lot of dependencies were pinned in a too strict way. This was especially bad for certain dependencies like `tokio`.
- remove duplicated entry: some dependencies were duplicated between the `dependencies` and `dev-dependencies` sections.
- bump dev-dependencies: some `dev-dependencies` were outdated.
- bump dependencies: some `dependencies` were outdated.
About the `dev-dependencies` and `dependency` bumps. I'm concerned, since dependabot should be taking care of this. I've double checked our configuration and everything seems fine. I'm really puzzled, since we got some dependabot PRs, but we missed a lot of updates.
> dependency cleanup

- CHANGELOG.md
- Cargo.toml
Preparing for the 0.10.0 release. It's important to make this release, since right now no published version of this library can fetch Sigstore's TUF repository.
> Tag 0.10.0 relase

- examples/cosign/verify/main.rs
- src/cosign/mod.rs
- src/cosign/verification_constraint/cert_subject_email_verifier.rs
- src/cosign/verification_constraint/cert_subject_url_verifier.rs
This allows for either an exact match [StringVerifier::ExactMatch]
or it allows for a regular expression [StringVerifier::Regex]
This supports the use case of trusting signatures from a
collection of email addresses e.g .*@redhat.com and or from a
collection of issuers.
Fixes: #299
- `CertSubjectEmailVerifier` is now constructed using either a `StringVerifer` enum. This supports exact string matches or regular expressions.
Docstrings and examples are updated to show how this is used.
> cosign: Allow use of regex in CertSubjectEmailVerifier

- Cargo.toml
- examples/cosign/verify/main.rs
- src/cosign/client.rs
- src/cosign/client_builder.rs
- src/cosign/constraint/annotation.rs
- src/cosign/mod.rs
- src/cosign/payload/simple_signing.rs
- src/cosign/signature_layers.rs
- src/cosign/verification_constraint/annotation_verifier.rs
- src/lib.rs
- src/mock_client.rs
- src/registry/config.rs
- src/registry/mod.rs
- src/registry/oci_caching_client.rs
- src/registry/oci_client.rs
- src/registry/oci_reference.rs
~~This is still in draft. We will wait for a new release of `oci-client` to include https://github.com/oras-project/rust-oci-client/pull/160~~
In some special cases, client needs to connect a proxy to pull signature via a proxy. This PR mainly accomplishes this.
* Config changes: Add proxy related items to `ClientConfig`
* Dep changes: update `oci-distribution` to `oci-client`
TODO
> Cosign | Add support for client to configure a proxy to pull signatures

- Cargo.toml
This is a bug fix PR. `regex` dependency is only used in cosign module now. Before this commit, when we only enable `cosign-rustls-tls` feature, the compilation will fail because regex dependency is not enabled.
> cosign: fix regex dependency import

- examples/cosign/verify-bundle/README.md
- examples/cosign/verify-bundle/run.sh
* Remove unneeded env var
* Use the README as the blob
* Avoid running sigstore/cosign to verify: the sigstore-rs example should be enough
Partially fixes #242: this is the last instance of COSIGN_EXPERIMENTAL but I don't think I've tested every single example yet so not sure if this is completely fixed or not...
> Simplify cosign verify-bundle example

- examples/bundle/README.md
- examples/bundle/main.rs
Add example of `sigstore::bundle` use to make it more visible that sigstore-rs does make it easy to use the new bundle format (as well as to automatically update the trust root). More specifically the example uses
* sigstore::bundle to sign and verify 
* sigstore::oauth to get a signing token
Fixes #406 
* examples: Added example of `sigstore::bundle` use
-->
See included README.md and `--help` output
> Examples: Add a minimal example of bundle sign/verify

- examples/cosign/verify-blob/main.rs
- examples/cosign/verify-bundle/main.rs
- src/cosign/mod.rs
* This changes cosign::verify_blob() cert argument: it is no longer PEM that is base64 encoded (on top of the encoding that is part of being a PEM), instead it is PEM as already documented.
* verify-blob example now works with certificates that are PEM or base64 PEM
* verify-blob example also trims signature
This makes verify-blob work with python-tuf outputs as well as the cosign outputs.
---
Fixes #288 
Note that _this changes the "cosign API"_: I imagined that this is mostly an internal module but if that is something you want to not change then this approach is probably not good.
> cosign: Make verify-blob compatible with sigstore-python

- .github/workflows/auto-publish-crates-upon-release.yml
- .github/workflows/conformance.yml
- .github/workflows/security-audit.yml
- .github/workflows/tests.yml
stops persisting git credentials unnecessarily and drops default permissions to none
> fix zizmor issues in github actions workflows

- Cargo.toml
- src/errors.rs
- src/oauth/openidflow.rs
Upgrade openidconnect to latest version. This is a major version change, which caused quite some breakage. The code has been fixed to build and all the tests are passing.
This upgrade allows us to drop the dependency on the really old 0.11 reqwest package.
This supersedes https://github.com/sigstore/sigstore-rs/pull/428
> chore(deps): upgrade openidconnect

- Cargo.toml
Add support for platform's certs store when using rustls
Adds a new feature `rustls-tls-native-roots`
The feature `rustls-tls-native-roots` allows the client to read platform's native certificate store when using rustls suites.
This useful when self-signed registry is used and the certs are loaded in the platform's trusted CA by commands like update-ca-certificates.
> oci-client: allow using native cert store with rustls

- Cargo.toml
- src/bundle/verify/verifier.rs
- src/cosign/client_builder.rs
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/cosign/verification_constraint/certificate_verifier.rs
- src/crypto/certificate_pool.rs
- src/registry/config.rs
- src/trust/mod.rs
- src/trust/sigstore/mod.rs
This PR resolves the Rustls webpki update issue, which was failing due to a breaking change. Webpki no longer exports `pki-types`, so an explicit `pki-types` dependency was added.  
Reference: https://github.com/rustls/webpki/pull/313
It also adds the `ring` feature, which is now needed because of [this breaking change](https://github.com/rustls/webpki/pull/302).
> build(deps): rustls webpki 0.103

- src/cosign/signature_layers.rs
- src/cosign/verification_constraint/certificate_verifier.rs
- src/crypto/mod.rs
Fix the issues flagged by clippy which prevent a local execution of `make test` (errors from the trunk code in [gist](https://gist.github.com/dmitris/a0ce8f38352016b1b0f7441a7cec4ea9)) - namely, due to the "overindentation", incorrect alignment of the text in Markdown lists ([#doc_lazy_continuation](https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation)).
An [example](https://github.com/sigstore/sigstore-rs/actions/runs/14739461994/job/41373616982?pr=457) of the trunk code (with minor README modification) failing in CI due to the clippy issues: 
NONE
N/A.  
Maybe it would be good to mention that you need to install [taplo](https://taplo.tamasfe.dev/cli/installation/binary.html) and how to do it?  (Or do we want to leave it as an "initiation exercise" for the …
> fix cargo clippy issues (overindentation)

- src/registry/config.rs
This config item allows client to pull signatures from a HTTP registry via a specified proxy.
> feat: add http proxy for ClientConfig

- examples/cosign/verify/README.md
- src/bundle/sign.rs
- src/cosign/verification_constraint/cert_subject_email_verifier.rs
- src/crypto/verification_key.rs
- src/trust/mod.rs
- src/trust/sigstore/mod.rs
The current command generates a warning (below), PR changes to the standard `--key` flag.
```sh
$ cosign sign -key cosign.key registry-testing.svc.lan/busybox
WARNING: the -key flag is deprecated and will be removed in a future release. Please use the --key flag instead.
```
Additionally, the change fixes some clippy issues.  `cargo clippy` output is clean with `1.88.0`.  PR also fixes `cargo +nightly clippy`  issue recorded in the [gist](https://gist.github.com/dmitris/070c05587b8be4fe0189edb5bd73c697).
The PR is an extended replica of https://github.com/sigstore/sigstore-rs/pull/474 (recreated for approval-technical reasons).
NONE
N/A
> update flag with double-dash (PR474 redux), address 'cargo clippy' issues
