- examples/verify/main.rs
- src/cosign/mod.rs
- src/cosign/signature_layers.rs
- src/crypto.rs
- src/lib.rs
- src/mock_client.rs
- src/registry.rs
- src/simple_signing.rs
> Add standard sigstore Apache2 license headers

- Cargo.toml
Get the new features out.
I'll take care of tagging a new release on GitHub once this is merged.
> Version bump to v0.1.0

- src/cosign/mod.rs
Solves clippy warning.
```release-note
NONE
```
> Derive `Default` on `cosign::ClientBuilder`

- README.md
This changed in sigstore/community#42
> Update README.md link to security process

- Cargo.toml
- src/cosign/signature_layers.rs
* Config changes (additions, deletions, updates)
* API additions—new endpoint, new response fields, or newly accepted request parameters
* Database changes (any)
* Anything noteworthy to an administrator running private sigstore instances (err on the side of over-communicating)
* New features and improvements, including behavioural changes, UI changes and CLI changes
* Bug fixes and fixes of previous known issues
* Deprecation warnings, breaking changes, or compatibility notes
> Prepare 0.3.0 release

- Cargo.toml
Changes:
* Add Fulcio intermediate CA certificate to intermediate pool - fixes issue #70
> Tag v0.3.2

- Cargo.toml
- src/crypto/certificate.rs
- src/crypto/verification_key.rs
This is a minor release that broke some APIs. This commit fixes all the issues introduced by the changes.
Supersedes #75
> Update to latest version of x509-parser

- README.md
> Add crate badges

- README.md
> Add OpenID Connect API to README

- README.md
Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>
> docs: Use doc.rs instead of github page in README.md

- src/tuf/constants.rs
Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>
> fix: Default to https on URL for Sigstore TUF repo

- src/cosign/bundle.rs
- src/registry/config.rs
- fix clippy lints
this is happening in the main branch
see https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
> fix clippy lints

- examples/key_interface/README.md
- examples/key_interface/main.rs
As mentioned https://github.com/sigstore/sigstore-rs/issues/27, we need some examples for users to
use the key_interface module, s.t. `crypto/signing_key`. 
* Added an example to use the `SigStoreSigner` in `crypto/signing_key`. Concretely, it Included a whole process of key pair generation, signing, exporting public/private key, importing public key and verifying the signature.
* Added a document for the example.
None
> feat: add example case and docs for key interface

- Cargo.toml
- src/crypto/signing_key/kdf.rs
Like #100 but with the required API change
> Update xsalsa20poly1305 requirement from 0.7.1 to 0.9.0

- README.md
Has a soft dependency on https://github.com/sigstore/sigstore-rs/pull/111
> Update readme to include new features

- Cargo.toml
> bump crate version

- src/rekor/apis/configuration.rs
Signed-off-by: Bob Callaway <bcallaway@google.com>
> update user-agent value to be specific to sigstore-rs

- CODEOWNERS
> Add Xynnn007 as a maintainer

- src/lib.rs
> Fix doc test failures in CI

- Cargo.toml
Updated dependency `rsa` version from `0.7.0-rc.1` to `0.7.0`
> fix: update rsa dependency to stable version 0.7.0

- src/crypto/signing_key/mod.rs
Fix typo in KeyPair trait doc comment
NONE
NONE
> Fix typo in KeyPair trait doc comment

- src/cosign/verification_constraint.rs
Fix typos in PublicKeyVerifier doc comments
NONE
NONE
> Fix typos in PublicKeyVerifier doc comments

- examples/cosign/verify/README.md
This commit updates the link in examples/cosign/verify/README.md to point to main.rs.
The motivation for this is that the current link will return a 404 "Not Found" because the path is missing 'cosign' in it. Adding 'cosign' will resolve the not found issue, but in that case it is just linking back to the same README.md.
Hopefully, linking to main.rs will make things clear about which code is being run in the cargo command that follows after the link.
NONE
NONE
> Update link to verification example

- src/fulcio/oauth.rs
Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>
This PR fixes the CI error 
```
error: deref which would be done by auto-deref
Error:    --> src/fulcio/oauth.rs:104:13
|
104 | /             &*format!(
105 | |                 "127.0.0.1:{}",
106 | |                 self.redirect_port.unwrap_or(DEFAULT_REDIRECT_PORT)
107 | |             ),
| |_____________^
|
= note: `-D clippy::explicit-auto-deref` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
help: try this
|
104 ~             &format!(
105 +                 "127.0.0.1:{}",
106 +                 self.redirect_port.unwrap_or(DEFAULT_REDIRECT_PORT)
107 ~             ),
|
```
> fix: CI error for auto deref

- src/cosign/signature_layers.rs
This commit fixes a typo in the CertificateSignature doc comment, and includes a suggestion for the doc comment for the from_certificate function.
NONE
NONE
> Fix typo and grammar in signature_layers.rs

- src/crypto/signing_key/ecdsa/ec.rs
- src/crypto/signing_key/ecdsa/mod.rs
- src/crypto/signing_key/ed25519.rs
- src/crypto/signing_key/rsa/keypair.rs
Fix typos in from_encrypted_pem doc comments
NONE
NONE
> Fix typos in from_encrypted_pem doc comments

- src/crypto/signing_key/ecdsa/ec.rs
- src/fulcio/oauth.rs
Fix typos in doc comments
NONE
NONE
> Fix typos in doc comments

- examples/cosign/verify/README.md
Currently, the following error will be generated when running the verify example:
```console
Cannot build sigstore repo data: Error reading fulcio certificate from disk: No such file or directory (os error 2)
```
This commit updates the path to point to fulcio.crt.pem in the same directory as rekor.pub.
NONE
NONE
> Update path to fulcio-cert in verify example

- src/cosign/signature_layers.rs
Fix typo in SignatureLayer::new doc comment
NONE
NONE
> Fix typo in SignatureLayer::new doc comment

- Cargo.toml
* Replace example dependency `docker_credential` with the one in `crates.io`
> feat: replace example dependency docker_credential

- src/cosign/payload/simple_signing.rs
Fix typo in simple_signing.rs
NONE
NONE
> Fix typo in simple_signing.rs

- src/cosign/constraint/signature.rs
- src/crypto/signing_key/kdf.rs
Fix typo in SecretBoxCipher doc comment
NONE
NONE
> Fix typo in SecretBoxCipher doc comment

- src/tuf/mod.rs
Fix typos in tuf/mod.rs
NONE
NONE
> Fix typos in tuf/mod.rs

- src/tuf/repository_helper.rs
Update target -> target_name for consistency
NONE
NONE
> Update target -> target_name for consistency

- README.md
Add verify-bundle example to README.md
NONE
NONE
> Add verify-bundle example to README.md

- src/fulcio/mod.rs
This commit adds a doc comment to TokenProvider::Static enum variant.
The motivation for adding this is that it was not obvious to me what the value of the second member, the String, was supposed to be. Hopefully having the comment will help clarify this.
NONE
NONE
> Add TokenProvider::Static doc comment

- README.md
The link to contributor documentation in `README.md` points to a non-existent file. This PR fixes the link to point to the [`CONTRIBUTORS.md`](https://github.com/sigstore/sigstore-rs/blob/main/CONTRIBUTORS.md) page, as well as disposing of a stray period in the middle of the sentence.
Fixes #224
NONE
NONE
> Fix link to contributor doc in readme

- examples/cosign/verify/main.rs
Correct a typo in verify/main.rs
NONE
NONE
> fix: correct typo in verify/main.rs

- Cargo.toml
- The newest version `picky` removes `ring` dependency with RustCrypto. By this updation, we can fully get rid of `ring` dependency for cosign verification.
Removed `ring` dependency when feature `["cosign-native-tls", "cached-client"]` are enabled.
Close https://github.com/sigstore/sigstore-rs/issues/187
> dep: update picky version to git rid of `ring`

- Cargo.toml
- README.md
- examples/cosign/verify-blob/.gitignore
- examples/cosign/verify-blob/README.md
- examples/cosign/verify-blob/main.rs
- examples/cosign/verify-bundle/README.md
- examples/cosign/verify-bundle/main.rs
- src/cosign/bundle.rs
- src/cosign/mod.rs
This commit adds a new example which verifies a blob created using cosign sign-blob. The function `SignedArtifactBundle::verify_blob` has been extracted and moved into the `cosign` module, which `SignedArtifactBundle::verify_blob` now calls.
NONE
NONE
> Add verify-blob example

- CHANGELOG.md
- Cargo.toml
Tag a new patch release to include a small fix.
> Release v0.7.1

- Cargo.toml
> chore(deps): update to latest version of picky

- Cargo.toml
> chore: add repository link to Cargo metadata

- CHANGELOG.md
- Cargo.toml
Once merged, I will tag the release
> Release 0.8.0

- src/bundle/verify/policy.rs
Remove unused code to address linter warning.
> fix linter warning

- CONTRIBUTORS.md
> CONTRIBUTORS.md: Add note about tests and building

- src/cosign/signature_layers.rs
> fix clippy complaint

- Cargo.toml
> Tag 0.11.0 release

- CONTRIBUTORS.md
PR fixes the markdown for a couple of the inter-document anchor links, to make them actually links.
> fix internal anchor links

- Cargo.toml
This is needed to bump tought to >= 0.20.0, which fixes several security advisories.
NONE
> build: Bump version to 0.12.0

- Cargo.toml
- src/crypto/certificate.rs
- src/registry/config.rs
> deps: Bump oci-client to 0.15

- Cargo.toml
Due to https://aws.github.io/aws-lc-rs/requirements/linux.html#linux-requirements
aws-lc-rs building on ppc64 relies on feature `bindgen`. This patch adds a compilation configuration on target arch. If the target is ppc64, the feature will be enabled.
Fixes #464
> fix: aws-lc-rs compilation on ppc64
